export const meta = {
  name: 'combo-batch7-nutley-differentiate',
  description: 'Reduce cross-city duplication on 3 high-overlap Nutley combos by foregrounding Nutley-specific local application while preserving all cited facts + entity-grounding',
  phases: [{ title: 'Differentiate', detail: 'one agent per service re-localizes shared passages to Nutley context' }],
}

phase('Differentiate')

const TARGETS = [
  { s: 'roof-thermal-imaging-inspections', e: 'nutleyRoofThermalImagingInspections', sib: 'belleville', ov: '51.6% Jaccard / 69.2% overlap',
    shared: 'The ASTM C1153 infrared procedure, the wet-insulation heat-capacity physics, the post-sunset thermal-anomaly read, core-cut verification, the non-destructive framing, and the cost FAQ are near-verbatim shared with the Belleville sibling.',
    local: 'Nutley thermal imaging is a FLAT/low-slope COMMERCIAL, INSTITUTIONAL, and MULTI-FAMILY service: foreground (1) the Franklin Avenue / Nutley Center downtown storefronts and mixed-use flat roofs AND the ON3 redevelopment campus that straddles Nutley and Clifton, where decades of recovers and re-coats on large institutional and commercial roofs trap moisture BETWEEN layers — exactly what an ASTM C1153 scan locates that a surface look misses; (2) the two-family and small multi-family flat-roofed stock where LANDLORD/portfolio decisions drive a scan before a costly tear-off; (3) the Third River / Yantacaw Park low-lying drainage corridor that feeds membrane saturation; (4) NON-INVASIVE reading from above over tenant-occupied units under New Jersey landlord-tenant notice; (5) the porch, dormer, and addition flats on Nutley\'s older single-family Colonials and Capes where hidden moisture reaches the deck before the interior shows it.' },
  { s: 'emergency-roof-repair', e: 'nutleyEmergencyRoofRepair', sib: 'belleville', ov: '42.9% Jaccard / 62.0% overlap',
    shared: 'The active-leak triage sequence (emergency tarp/dry-in, source isolation), the storm-versus-wear distinction, the flashing-failure leak-share (~90-95% at flashing per the NRCA), the cost range plus emergency premium, and the timestamped-photo documentation are near-verbatim shared with the Belleville sibling.',
    local: 'Nutley emergency roof repair spans a distinct stock: foreground (1) the older ~1890-1940 single-family Colonials and Capes of the five grammar-school sections (Spring Garden, Radcliffe, Lincoln, Washington, Yantacaw), where aging galvanized step and chimney flashing and brittle sealant open first in a storm; (2) the two-family and small multi-family homes plus the Franklin Avenue and ON3 flat-roofed commercial roofs, where a leak reaches shared roof structure and tenant units, so emergency access is coordinated under New Jersey landlord-tenant notice; (3) the mature street-tree canopy of Nutley\'s nine public parks, where branch-impact during nor\'easters drives the emergency call; (4) the Third River / Yantacaw Park low-lying drainage corridor where storm water concentrates on riverfront parcels; (5) owner and insurer documentation across the owner-occupied-majority stock.' },
  { s: 'rubber-roofing-epdm', e: 'nutleyRubberRoofingEpdm', sib: 'belleville', ov: '44.2% Jaccard / 61.5% overlap',
    shared: 'The EPDM 15-25-year InterNACHI lifespan, the ballasted / fully-adhered / mechanically-attached attachment methods, the seam and flashing detailing, the EPDM-vs-TPO contrast, and the cost FAQ are near-verbatim shared with the Belleville sibling.',
    local: 'Nutley EPDM rubber roofing is a LOW-SLOPE / FLAT-SECTION service across a single-family-majority township: foreground (1) the porch, dormer, and rear-addition flats on Nutley\'s older single-family Colonials and Capes, where an EPDM membrane covers exactly what the steep asphalt roof omits; (2) the two-family and small multi-family flat-roofed stock plus the Franklin Avenue / Nutley Center storefronts and the ON3 commercial roofs that straddle Nutley and Clifton, which carry the bulk of the membrane work; (3) tenant-occupied access under New Jersey landlord-tenant notice on the rental and small multi-family roofs; (4) the Third River / Yantacaw Park low-lying drainage that makes ponding control and seam integrity the priority; (5) the mature-canopy debris from Nutley\'s nine public parks that abrades and punctures an exposed or ballasted membrane.' },
]

function prompt(t) {
  return `You are reducing cross-city DUPLICATION on ONE Nutley (Township of Nutley, NJ) service×city combo while raising its local value, for a local-SEO roofing site. Service: "${t.s}". File to rewrite: src/data/combo-content/nutley/${t.s}.ts (export const ${t.e}: ComboContent).

WHY: a 7-city near-duplicate analysis found this combo at ${t.ov} with the ${t.sib} version of the same service, because the content is dominated by standardized facts identical city-to-city. ${t.shared} Your job: re-localize so Nutley's distinct local application DOMINATES the page and the shared facts become a supporting minority — WITHOUT deleting any cited fact.

STEP 1 — READ all three:
- src/data/combo-content/nutley/${t.s}.ts (the file you will rewrite — it ALREADY passes the gate and carries adversarial-review corrections + entity-grounding; confirm export "${t.e}", serviceId "${t.s}", cityId 'nutley'. PRESERVE every fact and every corrected source attribution already in it.)
- src/data/combo-content/${t.sib}/${t.s}.ts (the sibling you must DIVERGE from — do not mirror its sentence structure or order)
- .planning/content-system/combo-batch7-nutley/_NUTLEY-BRIEF.md (render contract + hard rules + Nutley facts + §0 ENTITY-GROUNDING)

STEP 2 — REWRITE the Nutley file to foreground these verified Nutley distinctives:
${t.local}

ENTITY-GROUNDING — PRESERVE EXACTLY (do NOT change these two fields):
- directAnswer: keep the existing entity-grounded value verbatim (it already reads "Newark Quality Roofing is a roofing contractor providing ${t.s.replace(/-/g,' ')} across Nutley, New Jersey, and Essex County, … as a registered New Jersey Home Improvement Contractor"). Do not rewrite it.
- definition: keep the existing 'definition' field value BYTE-FOR-BYTE (it is the canonical service definition; altering it breaks entity-stability). Copy it through unchanged.

RULES (do not break the gate — this file currently passes):
- PRESERVE EVERY CITED FACT AND NAMED SOURCE currently in the file (ASTM C1153, InterNACHI lifespans, NRCA/ARMA, Modernize/HomeAdvisor/Angi/HomeGuide cost ranges, N.J.A.C. sections, IRC sections, IBHS, IIBEC, Triple-I/NAIC, the full N.J.A.C. 5:23-6.4 statutory recover list "wood shake, slate, clay, cement, or asbestos-cement tile"). Relocate them INTO the localized narrative; never delete a fact or invent a new number. Introduce NO new hard number not already in the file or implied by the brief. Keep the insurance/proof-of-loss framing as the contractual ~60-day proof-of-loss policy term per United Policyholders and NAIC (NEVER a statutory NJ DOBI claim deadline). Keep wind-uplift attributed to "per IIBEC" (NEVER RICOWI). Keep attic ventilation qualitative (NEVER the NRCA "up to 25%" figure). Keep housing QUALITATIVE (NEVER a published owner/renter or multi-unit %).
- Materially REPHRASE the shared standardized passages in Nutley-contextualized language so they are no longer near-verbatim with the ${t.sib} sibling (FACTS stay; FRAMING localizes). Cut the verbatim shingle overlap substantially.
- Keep it answer-first: overview[0]/challenges[0]/process[0] each a ≤40-word FIGURE-FREE bold lead; each faq answer's first sentence ≤40 words and definitive. Count standalone " — " em-dash tokens as words; stay under 40.
- Schema caps: overview 3-5, challenges 2-4, process 2-4, faqs 3-6 (keep exactly one cost FAQ). metaDescription ≤160 chars, no ** markdown.
- CREDENTIAL: NQR is "a registered New Jersey Home Improvement Contractor" / "fully insured" — NEVER "licensed" for NQR (keep third-party "licensed public adjuster/engineer/Construction Official/asbestos abatement" cites). NO de-fab literals (GAF Certified, same-day, 24/7, 15+ years, 500+, top-rated, response-time claims, manufacturer-certification claims). NO will/should/need-to/must modality in declaratives (FAQ questions exempt). NO ** markdown in raw fields (whyChooseUs, pricing.range, pricing.note, metaDescription, conversionHooks.*, faq question). NO links/URLs. NO city-specific heat-island/wind degree numbers.
- NUTLEY GEOGRAPHY: inner-ring township NORTH of Newark; the THIRD RIVER (also called the YANTACAW) runs THROUGH Nutley (through Yantacaw Park and Memorial Park); the PASSAIC RIVER forms Nutley's WESTERN boundary — do NOT swap them. ON3 (the former Hoffmann-La Roche campus) STRADDLES Nutley AND Clifton — never "entirely in Nutley." Borders Belleville, Bloomfield, Newark, Glen Ridge, and Montclair (Essex) and Clifton (Passaic). NO reservation. Verified sections only: the five grammar-school sections (Spring Garden, Radcliffe, Lincoln, Washington, Yantacaw), Avondale (eastern), Franklin Avenue (commercial spine / Nutley Center downtown — an AVENUE, not a section), and The Enclosure (a historic enclave). Do NOT import Belleville's "Second River / Soho / Washington Avenue / Route 21" framing, Irvington's "Vailsburg/I-78," East Orange's "flat Watsessing plain," Orange's "Watchung-ridge," or Bloomfield's "town center / Garden State Parkway."
- NUTLEY HISTORIC: a BINDING local COA — Nutley's Historic Preservation ordinance (Chapter 410) designates a "Historic District of the Third River and Environs" where exterior roofing requires a Certificate of Appropriateness from the Nutley Historic Preservation Committee, a SEPARATE approval from the construction permit; verify the specific parcel against the Township's official historic-district map. Cite "Chapter 410" generically (Chapter 272 is the separate Construction Codes chapter — do NOT conflate). The Enclosure is National-Register-listed (1974) but its LOCAL designation is LIKELY-but-UNCONFIRMED — write "verify the specific parcel," never a flat COA assertion. Do NOT name a Construction Official, do NOT publish a fabricated landmark list, do NOT invent COA fees/fines/buffers. Per the NPS, a Register listing alone places no restriction on a private owner. Do NOT import Bloomfield's Chapter 302 / Property-List gate or Orange's four-district framing.
- Apostrophes inside single-quoted TS strings MUST be escaped (Nutley\\'s) — unescaped apostrophes break the build.

OUTPUT: write the COMPLETE rewritten file to .planning/content-system/combo-batch7-nutley/${t.s}.diff.ts — first line EXACTLY "import type { ComboContent } from '../schema';", blank line, then "export const ${t.e}: ComboContent = {", keep serviceId/cityId, KEEP directAnswer + definition unchanged, end with "};". Output ONLY valid TypeScript (no code fences, no commentary). Do NOT edit any file under src/.

Return one line: "${t.s}: rewritten, <N faqs>, foregrounded <one-phrase Nutley local angle>".`
}

const results = await parallel(TARGETS.map(t => () => agent(prompt(t), { label: `diff:${t.s}`, phase: 'Differentiate' })))
log(`Differentiate complete: ${results.filter(Boolean).length}/${TARGETS.length}`)
return { done: results.filter(Boolean).length, total: TARGETS.length, statuses: results }
