import type { NextConfig } from "next";
// Generated by scripts/build-url-classification.ts (regenerated each build via `prebuild`).
// 176 permanent 301s = 168 combo (CONSOLIDATE / 301) + 8 legacy hub redirects.
import generatedRedirects from "./src/generated/redirects.generated.mjs";

const nextConfig: NextConfig = {
  trailingSlash: false,
  async redirects() {
    return [
      // ── Preserved manual redirects ──────────────────────────────────────────
      {
        source: '/flat-roof-installation-newark-nj',
        destination: '/flat-roof-installation-repair-newark-nj',
        permanent: true,
      },
      {
        source: '/:path*',
        has: [{ type: 'host', value: 'www.newarkqualityroofing.com' }],
        destination: 'https://newarkqualityroofing.com/:path*',
        permanent: true,
      },
      // ── Hub migrations (D-07): old hub URLs 301 to renamed canonical hubs ─────
      // /services + /locations point at renamed core pages; /resources points at
      // the KB catch-all hub index (built in Plan 05), NOT a renamed core page.
      { source: '/services', destination: '/roofing-services', permanent: true },
      { source: '/locations', destination: '/service-areas', permanent: true },
      { source: '/resources', destination: '/roofing-knowledge-base', permanent: true },
      // ── Generated combo + legacy redirects (D-05): 168 + 8 = 176 ─────────────
      ...generatedRedirects,
    ];
  },
};

export default nextConfig;
