import type { NextConfig } from "next";
// Generated by scripts/build-url-classification.ts (regenerated each build via `prebuild`).
// 225 permanent 301s = 225 combo (CONSOLIDATE / 301) + 0 legacy hub redirects
// (168 prior combo redirects + 57 Newark combos consolidated into their service pages).
import generatedRedirects from "./src/generated/redirects.generated.mjs";

const nextConfig: NextConfig = {
  trailingSlash: false,
  async redirects() {
    return [
      // ── Canonical host (2026-09-16): the Vercel production alias served the site as a
      //    second, indexable copy. Send it to the custom domain. ──
      { source: "/:path*", has: [{ type: "host", value: "newarkqualityroofing.vercel.app" }], destination: "https://newarkqualityroofing.com/:path*", permanent: true },
      // ── City slug migration: roofing-in-{city}-nj -> roof-repair-and-installation-in-{city}-nj (21) ──
      { source: "/roofing-in-newark-nj", destination: "/roof-repair-and-installation-in-newark-nj", permanent: true },
      { source: "/roofing-in-east-orange-nj", destination: "/roof-repair-and-installation-in-east-orange-nj", permanent: true },
      { source: "/roofing-in-orange-nj", destination: "/roof-repair-and-installation-in-orange-nj", permanent: true },
      { source: "/roofing-in-west-orange-nj", destination: "/roof-repair-and-installation-in-west-orange-nj", permanent: true },
      { source: "/roofing-in-montclair-nj", destination: "/roof-repair-and-installation-in-montclair-nj", permanent: true },
      { source: "/roofing-in-bloomfield-nj", destination: "/roof-repair-and-installation-in-bloomfield-nj", permanent: true },
      { source: "/roofing-in-belleville-nj", destination: "/roof-repair-and-installation-in-belleville-nj", permanent: true },
      { source: "/roofing-in-nutley-nj", destination: "/roof-repair-and-installation-in-nutley-nj", permanent: true },
      { source: "/roofing-in-irvington-nj", destination: "/roof-repair-and-installation-in-irvington-nj", permanent: true },
      { source: "/roofing-in-maplewood-nj", destination: "/roof-repair-and-installation-in-maplewood-nj", permanent: true },
      { source: "/roofing-in-south-orange-nj", destination: "/roof-repair-and-installation-in-south-orange-nj", permanent: true },
      { source: "/roofing-in-livingston-nj", destination: "/roof-repair-and-installation-in-livingston-nj", permanent: true },
      { source: "/roofing-in-millburn-nj", destination: "/roof-repair-and-installation-in-millburn-nj", permanent: true },
      { source: "/roofing-in-cedar-grove-nj", destination: "/roof-repair-and-installation-in-cedar-grove-nj", permanent: true },
      { source: "/roofing-in-verona-nj", destination: "/roof-repair-and-installation-in-verona-nj", permanent: true },
      { source: "/roofing-in-glen-ridge-nj", destination: "/roof-repair-and-installation-in-glen-ridge-nj", permanent: true },
      { source: "/roofing-in-caldwell-nj", destination: "/roof-repair-and-installation-in-caldwell-nj", permanent: true },
      { source: "/roofing-in-essex-fells-nj", destination: "/roof-repair-and-installation-in-essex-fells-nj", permanent: true },
      { source: "/roofing-in-fairfield-nj", destination: "/roof-repair-and-installation-in-fairfield-nj", permanent: true },
      { source: "/roofing-in-north-caldwell-nj", destination: "/roof-repair-and-installation-in-north-caldwell-nj", permanent: true },
      { source: "/roofing-in-roseland-nj", destination: "/roof-repair-and-installation-in-roseland-nj", permanent: true },
      // ── Service slug migration: /{service} -> /{service}-in-newark-nj (65) ──
      // Service hubs moved to a local-intent URL parallel to the city pages, so
      // they read distinctly from the combo "{service}-{city}-nj" pattern. The
      // Newark combos (URL-Classification.csv) 301 straight to these new slugs.
      { source: "/aging-roof-replacement", destination: "/aging-roof-replacement-in-newark-nj", permanent: true },
      { source: "/asphalt-shingle-roof-replacement", destination: "/asphalt-shingle-roof-replacement-in-newark-nj", permanent: true },
      { source: "/asphalt-shingle-roofing", destination: "/asphalt-shingle-roofing-in-newark-nj", permanent: true },
      { source: "/built-up-roofing", destination: "/built-up-roofing-in-newark-nj", permanent: true },
      { source: "/cedar-shake-roof-replacement", destination: "/cedar-shake-roof-replacement-in-newark-nj", permanent: true },
      { source: "/cedar-shake-roofing", destination: "/cedar-shake-roofing-in-newark-nj", permanent: true },
      { source: "/chimney-flashing-repair", destination: "/chimney-flashing-repair-in-newark-nj", permanent: true },
      { source: "/commercial-metal-roofing", destination: "/commercial-metal-roofing-in-newark-nj", permanent: true },
      { source: "/commercial-roof-installation", destination: "/commercial-roof-installation-in-newark-nj", permanent: true },
      { source: "/commercial-roof-repair", destination: "/commercial-roof-repair-in-newark-nj", permanent: true },
      { source: "/commercial-roof-replacement", destination: "/commercial-roof-replacement-in-newark-nj", permanent: true },
      { source: "/custom-roof-design-consultation", destination: "/custom-roof-design-consultation-in-newark-nj", permanent: true },
      { source: "/emergency-roof-repair", destination: "/emergency-roof-repair-in-newark-nj", permanent: true },
      { source: "/energy-efficient-roofing-solutions", destination: "/energy-efficient-roofing-solutions-in-newark-nj", permanent: true },
      { source: "/epdm-commercial-roofing", destination: "/epdm-commercial-roofing-in-newark-nj", permanent: true },
      { source: "/fascia-installation-repair", destination: "/fascia-installation-repair-in-newark-nj", permanent: true },
      { source: "/fire-damage-roof-replacement", destination: "/fire-damage-roof-replacement-in-newark-nj", permanent: true },
      { source: "/flat-roof-installation-repair", destination: "/flat-roof-installation-repair-in-newark-nj", permanent: true },
      { source: "/flat-roof-replacement", destination: "/flat-roof-replacement-in-newark-nj", permanent: true },
      { source: "/full-roof-tear-off", destination: "/full-roof-tear-off-in-newark-nj", permanent: true },
      { source: "/green-roof-installation", destination: "/green-roof-installation-in-newark-nj", permanent: true },
      { source: "/gutter-guard-installation", destination: "/gutter-guard-installation-in-newark-nj", permanent: true },
      { source: "/gutter-installation-repair", destination: "/gutter-installation-repair-in-newark-nj", permanent: true },
      { source: "/hail-damage-roof-repair", destination: "/hail-damage-roof-repair-in-newark-nj", permanent: true },
      { source: "/historic-roof-restoration", destination: "/historic-roof-restoration-in-newark-nj", permanent: true },
      { source: "/infrared-roof-leak-detection", destination: "/infrared-roof-leak-detection-in-newark-nj", permanent: true },
      { source: "/insurance-roof-replacement", destination: "/insurance-roof-replacement-in-newark-nj", permanent: true },
      { source: "/metal-roof-installation-repair", destination: "/metal-roof-installation-repair-in-newark-nj", permanent: true },
      { source: "/metal-roof-replacement", destination: "/metal-roof-replacement-in-newark-nj", permanent: true },
      { source: "/modified-bitumen-roofing", destination: "/modified-bitumen-roofing-in-newark-nj", permanent: true },
      { source: "/pvc-roofing", destination: "/pvc-roofing-in-newark-nj", permanent: true },
      { source: "/re-roofing", destination: "/re-roofing-in-newark-nj", permanent: true },
      { source: "/residential-roof-installation", destination: "/residential-roof-installation-in-newark-nj", permanent: true },
      { source: "/roof-cleaning-moss-removal", destination: "/roof-cleaning-moss-removal-in-newark-nj", permanent: true },
      { source: "/roof-deck-repair-replacement", destination: "/roof-deck-repair-replacement-in-newark-nj", permanent: true },
      { source: "/roof-flashing-installation-repair", destination: "/roof-flashing-installation-repair-in-newark-nj", permanent: true },
      { source: "/roof-ice-dam-prevention", destination: "/roof-ice-dam-prevention-in-newark-nj", permanent: true },
      { source: "/roof-inspection", destination: "/roof-inspection-in-newark-nj", permanent: true },
      { source: "/roof-leak-repair", destination: "/roof-leak-repair-in-newark-nj", permanent: true },
      { source: "/roof-maintenance-programs", destination: "/roof-maintenance-programs-in-newark-nj", permanent: true },
      { source: "/roof-overlay-installation", destination: "/roof-overlay-installation-in-newark-nj", permanent: true },
      { source: "/roof-repair", destination: "/roof-repair-in-newark-nj", permanent: true },
      { source: "/roof-replacement", destination: "/roof-replacement-in-newark-nj", permanent: true },
      { source: "/roof-replacement-after-leak", destination: "/roof-replacement-after-leak-in-newark-nj", permanent: true },
      { source: "/roof-replacement-cost", destination: "/roof-replacement-cost-in-newark-nj", permanent: true },
      { source: "/roof-thermal-imaging-inspections", destination: "/roof-thermal-imaging-inspections-in-newark-nj", permanent: true },
      { source: "/roof-vent-installation-repair", destination: "/roof-vent-installation-repair-in-newark-nj", permanent: true },
      { source: "/roof-waterproofing", destination: "/roof-waterproofing-in-newark-nj", permanent: true },
      { source: "/rubber-roofing-epdm", destination: "/rubber-roofing-epdm-in-newark-nj", permanent: true },
      { source: "/silicone-elastomeric-roof-coating", destination: "/silicone-elastomeric-roof-coating-in-newark-nj", permanent: true },
      { source: "/silicone-roof-coating", destination: "/silicone-roof-coating-in-newark-nj", permanent: true },
      { source: "/skylight-installation-repair", destination: "/skylight-installation-repair-in-newark-nj", permanent: true },
      { source: "/slate-roof-installation-repair", destination: "/slate-roof-installation-repair-in-newark-nj", permanent: true },
      { source: "/slate-roof-replacement", destination: "/slate-roof-replacement-in-newark-nj", permanent: true },
      { source: "/soffit-installation-repair", destination: "/soffit-installation-repair-in-newark-nj", permanent: true },
      { source: "/solar-panel-roofing-installation", destination: "/solar-panel-roofing-installation-in-newark-nj", permanent: true },
      { source: "/solar-shingle-installation", destination: "/solar-shingle-installation-in-newark-nj", permanent: true },
      { source: "/spray-foam-roofing", destination: "/spray-foam-roofing-in-newark-nj", permanent: true },
      { source: "/storm-damage-roof-repair", destination: "/storm-damage-roof-repair-in-newark-nj", permanent: true },
      { source: "/storm-damage-roof-replacement", destination: "/storm-damage-roof-replacement-in-newark-nj", permanent: true },
      { source: "/tile-roof-installation-repair", destination: "/tile-roof-installation-repair-in-newark-nj", permanent: true },
      { source: "/tile-roof-replacement", destination: "/tile-roof-replacement-in-newark-nj", permanent: true },
      { source: "/tpo-roofing-installation", destination: "/tpo-roofing-installation-in-newark-nj", permanent: true },
      { source: "/wind-damage-roof-repair", destination: "/wind-damage-roof-repair-in-newark-nj", permanent: true },
      { source: "/wood-shake-roofing", destination: "/wood-shake-roofing-in-newark-nj", permanent: true },
      // ── Preserved manual redirects ──────────────────────────────────────────
      {
        // Old slug -> the service page directly. The service hub now lives at the
        // "-in-newark-nj" slug, so point straight at it (avoids a 301->301 chain
        // through the /flat-roof-installation-repair service migration redirect).
        source: '/flat-roof-installation-newark-nj',
        destination: '/flat-roof-installation-repair-in-newark-nj',
        permanent: true,
      },
      {
        source: '/:path*',
        has: [{ type: 'host', value: 'www.newarkqualityroofing.com' }],
        destination: 'https://newarkqualityroofing.com/:path*',
        permanent: true,
      },
      // ── Hub migrations (D-07): old hub URLs 301 to renamed canonical hubs ─────
      // /services + /locations point at renamed core pages; /resources points at
      // the KB catch-all hub index (built in Plan 05), NOT a renamed core page.
      { source: '/services', destination: '/roofing-services', permanent: true },
      { source: '/locations', destination: '/service-areas', permanent: true },
      { source: '/resources', destination: '/roofing-knowledge-base', permanent: true },
      // ── Reverted "-1" slug migration (2026-07-26, branch slug-migration-append-1) ──
      // Commit 0d1d4bb set URL_SLUG_SUFFIX='-1', which suffixed every public slug
      // AND the sitemap. It shipped, was reverted the same day, but no reverse
      // redirect was added — so 1,530 URLs Google crawled 07-26..07-30 have been
      // hard 404s ever since (dynamicParams=false in src/app/[slug]/page.tsx).
      // Collision-safe: 0 of the 1,127 live sitemapped URLs end in "-1".
      // The KB rules must precede the flat one: the KB migration suffixed BOTH
      // path segments (/roofing-knowledge-base-1/roof-problems-1).
      {
        source: '/roofing-knowledge-base-1/:cluster([^/]+)-1',
        destination: '/roofing-knowledge-base/:cluster',
        permanent: true,
      },
      // Single-segment only ([^/]+), so this can never match /_next/* or any
      // other nested path.
      { source: '/:slug([^/]+)-1', destination: '/:slug', permanent: true },
      // ── Generated combo redirects (D-05): 225 combo + 0 legacy = 225 ─────────
      ...generatedRedirects,
    ];
  },
  async rewrites() {
    return [
      // robots.txt advertises /sitemap.xml. A hand-written public/sitemap.xml used to
      // shadow the dynamic index and silently dropped the 'hubs' segment (2026-09-27).
      { source: '/sitemap.xml', destination: '/sitemap-index.xml' },
    ];
  },
};

export default nextConfig;
