// Deterministic ≤40w lead trims for the residential-roof-types articles sub-batch.
// Sets each (articleId, field) -> full new value on _authored.json. field 'directAnswer'
// sets a.directAnswer; 'sNb0' sets a.sections[N].body[0]. Every fact/source preserved;
// long first sentences split at a clause boundary; bold spans tightened; 'leading'->'chief'.
// Run: node .planning/content-system/articles-batch/_apply-trims.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const F = join(HERE, '_authored.json');
const data = JSON.parse(readFileSync(F, 'utf8'));
const byId = new Map(data.articles.map((a) => [a.articleId, a]));

const TRIMS = [
  ['residential-roof-installation-signs', 's0b0', "**A roof reaches the end of its life at its material lifespan: 3-tab asphalt lasts 20 years, architectural asphalt 30 years, metal 40 to 80 years, and natural slate 60 to 150 years**, per the InterNACHI life-expectancy chart. The actual asphalt figure varies up to 40% with climate and maintenance, per the NRCA."],
  ['residential-roof-installation-signs', 's1b0', "**A spongy or sagging roof deck signals moisture-rotted sheathing that a surface cover cannot correct**, the condition a deck-to-ridge installation replaces during tear-off, per GAF inspection guidance. An undersized or unbalanced attic ventilation system shortens roof life, per the NRCA and ARMA."],
  ['residential-roof-installation-signs', 's2b0', "**Damage across more than 25–30% of the roof area crosses the contractor-consensus 25% rule**, the threshold above which a full installation costs less than continued repair, per roofing industry guidance. A material-class change, a missing ice barrier, or new construction also calls for a full installation, per the International Residential Code."],
  ['residential-roof-installation-decision', 'directAnswer', "**A full residential roof installation's chief advantage is a complete deck-to-ridge system that corrects deck rot and recoups roughly 60 to 68% at resale; its chief drawback is a $10,000 to $25,000-plus cost** (InterNACHI, Zillow, HomeAdvisor)."],
  ['residential-roof-installation-decision', 's0b0', "**A full roof installation** replaces the entire weatherproof assembly — ice barrier, underlayment, flashing, cover, and ventilation — rather than a single failed detail. It corrects moisture-rotted decking and undersized attic ventilation that a surface cover cannot address, per GAF inspection guidance."],
  ['residential-roof-installation-decision', 's1b0', "**The drawback of a full installation** is its cost: a typical New Jersey home runs $10,000 to $25,000 or more, per HomeAdvisor and Modernize. NJ ranges sit 10 to 40% above national figures because labor accounts for roughly 60 to 70% of an asphalt install and NJ code is stricter, per HomeGuide and Integrity Home Exteriors."],
  ['residential-roof-installation-decision', 's2b0', "**A full installation fits** new construction or a new addition, a roof at or past its material life, a rotted deck, or a change of roofing material class. It also fits damage across more than 25 to 30% of the roof area under the contractor-consensus 25% rule (3-tab asphalt lasts 20 years, architectural 30, per InterNACHI)."],
  ['asphalt-shingle-roofing-signs', 'directAnswer', "**The signs you need a new asphalt shingle roof are a roof at or past its 20-to-30-year life, granule loss over 30%, curling or buckling shingles, cracked or wind-stripped shingles, and damage across more than 25–30%**, per the InterNACHI life-expectancy chart, GAF, and NRCA guidance."],
  ['asphalt-shingle-roofing-signs', 's0b0', "**An asphalt roof reaches end-of-life at 20 years for 3-tab shingles and 30 years for architectural shingles**, the rated material lifespans per the InterNACHI life-expectancy chart. Actual asphalt life varies up to 40% with climate, install, and maintenance, per the NRCA."],
  ['asphalt-shingle-roofing-signs', 's1b0', "**The surface signs of a failing asphalt roof are granule loss over 30%, curling or cupping or buckling shingles, cracked or wind-stripped shingles, and spreading ceiling stains**, per GAF, ARMA, and NRCA guidance."],
  ['asphalt-shingle-roofing-signs', 's2b0', "**Damage across more than 25–30% of the roof area crosses the contractor-consensus 25% rule, the threshold above which a full re-roof costs less than continued spot repair**, per roofing industry guidance. A roof carrying 2 or more layers or a water-soaked deck forces complete removal, per N.J.A.C. 5:23-6.4."],
  ['asphalt-shingle-roofing-cost-guide', 's0b0', "**Asphalt shingle roofing in New Jersey costs $5.50 to $9.50 per square foot for 3-tab and $6.50 to $11.00 for architectural shingles**, per Josten Roofing NJ pricing. National asphalt installs at $3.50 to $11.00 per square foot, or $350 to $1,100 per square of 100 square feet, per HomeGuide."],
  ['asphalt-shingle-roofing-cost-guide', 's1b0', "**Material tier, tear-off and deck repair, and labor** drive the installed price of an asphalt shingle roof. Architectural shingles, multi-layer removal, and New Jersey labor each add cost above the base 3-tab figure, per Josten Roofing NJ, the NJ Rehabilitation Subcode, and HomeGuide."],
  ['asphalt-shingle-roofing-decision', 's0b0', "**Asphalt shingles** are the most common residential roof covering, on roughly 73% of US homes per 2024 roofing-market data. Architectural shingles last 30 years at a wind rating up to 130 mph with the manufacturer 6-nail pattern, per the InterNACHI life-expectancy chart and ARMA."],
  ['asphalt-shingle-roofing-decision', 's1b0', "**Asphalt's short lifespan** is its central drawback, since 3-tab shingles last 20 years and architectural shingles 30 years against slate at 60 to 150, metal at 40 to 80, and clay tile past 100, per the InterNACHI life-expectancy chart. Actual asphalt life varies up to 40% with climate, install, and ventilation, per the NRCA."],
  ['slate-roof-installation-repair-signs', 's2b0', "**Full slate replacement** applies only when more than 30 to 40 percent of fasteners corrode beyond repair or the deck rots. The stone rarely sets the trigger, lasting 60 to 150 years, per the InterNACHI life-expectancy chart and National Slate Association guidance."],
  ['slate-roof-installation-repair-cost-guide', 'directAnswer', "**Slate roof repair runs $500 to $2,100 in New Jersey, with broken-tile replacement at $50 to $300 per tile, flashing or fastener work at $400 to $3,000, and installation roughly $10 to $30 per square foot** (HomeGuide / Angi / Josten Roofing NJ)."],
  ['slate-roof-installation-repair-cost-guide', 's1b0', "**The price of slate work** tracks whether the job is a targeted repair or a code-triggered full removal. It also tracks how closely replacement slate matches the existing tile, the deck condition under the slate weight, and the labor that mobilizes slate-specific equipment, per N.J.A.C. 5:23-6.4 and HomeGuide cost data."],
  ['slate-roof-installation-repair-decision', 's1b0', "**Slate carries a high cost and a substantial weight**: repair runs $500 to $2,100 (typical near $1,400), flashing or fastener work $400 to $3,000, and restoration $2,500 to $10,000-plus, per HomeGuide and Angi cost data. The stone weighs far more than asphalt shingles, and installation runs roughly $10 to $30 per square foot, per Josten Roofing NJ."],
  ['wood-shake-roofing-signs', 'directAnswer', "**The signs you need wood shake roofing are shakes cupped, split, or warped across the roof, a shake that cracks under the flex test, moss or lichen, rot on shaded slopes, or daylight through the deck**, per InterNACHI, the Cedar Shake & Shingle Bureau, and This Old House."],
  ['wood-shake-roofing-signs', 's0b0', "**A cedar roof reaches end-of-life** when wood roofing passes the 25-year mark on the InterNACHI life-expectancy chart, or when cedar shake passes the 20-to-40-year range the Cedar Shake & Shingle Bureau sets. Maintenance decides where in that span a roof lands."],
  ['wood-shake-roofing-signs', 's1b0', "**The surface and moisture signs are cupped, split, or warped shakes, moss or lichen colonizing the surface, and rot beneath shakes on north-facing or shaded slopes**. Moisture, not insects, drives most premature cedar failure, per Cedar Shake & Shingle Bureau and NRCA guidance."],
  ['wood-shake-roofing-signs', 's2b0', "**Damaged area or deck decay favors replacement** when shakes cup or split across more than 25 to 30% of the roof, or when daylight shows through the deck from inside the attic. That crosses the contractor-consensus threshold above which full replacement costs less than continued shake-by-shake repair."],
  ['wood-shake-roofing-cost-guide', 's2b0', "**Wood shake roofing costs roughly 10 to 40% more in New Jersey than national figures**, driven by higher regional labor and stricter NJ code, per NHI Contractors NJ pricing. A cedar install lands at $10 to $20-plus per square foot here."],
  ['wood-shake-roofing-decision', 's0b0', "**Wood shake's chief advantage is durability built into the wood itself: western red cedar carries natural extractives that resist decay**. A maintained cedar shake roof lasts 20 to 40 years, with cedar shingle reaching 30 to 50 years, per the Cedar Shake & Shingle Bureau, against the single 25-year \"Wood\" figure on the InterNACHI life-expectancy chart."],
  ['wood-shake-roofing-decision', 's1b0', "**Wood shake's central drawback is that moisture, not insects, drives most premature cedar failure**, so the assembly needs at least 1.5 inches of air space beneath the shakes or it decays early. The roof carries recurring fungicide or algaecide maintenance at $0.15 to $0.60 per square foot, per Cedar Shake & Shingle Bureau, NRCA, and HomeGuide guidance."],
  ['wood-shake-roofing-decision', 's2b0', "**Wood shake fits an Essex County home** whose architectural character specifies cedar, built on a ventilated assembly with at least 1.5 inches of air space, and owned by someone committed to recurring moisture-management maintenance. The Cedar Shake & Shingle Bureau ties that maintenance to the upper end of the 20-to-40-year range."],
  ['metal-roof-installation-repair-signs', 's0b0', "**Backed-out fasteners, failed washer seals, and separated or lifted standing seams** open the leak points on a metal roof. Sealant at metal laps typically fails in 5 to 10 years, and thermal expansion stresses long panel runs, per roofing trade guidance and the Metal Construction Association."],
  ['metal-roof-installation-repair-signs', 's1b0', "**Cut-edge corrosion, rust streaking, and oil-canning or buckling** signal a metal roof failing at the coating or the attachment. The protective coating breaks at a cut or scratch, and thermal expansion stresses a panel fastened without adequate clip movement, per the Metal Construction Association."],
  ['metal-roof-installation-repair-signs', 's2b0', "**A metal roof crosses to replacement at or past its 40-to-80-year life**, when panel corrosion exceeds 20 to 25% of the area, or when seam-connection damage exceeds 25%. These are the contractor-consensus thresholds above which full replacement returns more value than continued section repair, per InterNACHI and roofing industry guidance."],
  ['metal-roof-installation-repair-decision', 's1b0', "**Metal roofing costs more to install than asphalt and demands thermal-movement management**, installing at $9 to $16 per square foot in New Jersey, 10 to 40% above national figures, per Josten Roofing NJ and Integrity Home Exteriors. Architectural asphalt installs at $6.50 to $11 per square foot by comparison."],
  ['flat-roof-installation-repair-signs', 's2b0', "**Ponding water held more than 48 hours after rain** counts as a defect that breaks down membrane seams, because a flat roof needs at least one-quarter inch per foot of slope to drain, per the NRCA and ARMA. Persistent ponding signals a slope or drainage failure rather than a single seam, and correcting it calls for tapered insulation that rebuilds the slope toward the drains."],
  ['flat-roof-installation-repair-cost-guide', 's0b0', "**Flat-roof repair costs $2.50 to $10.00 per square foot, or $300 to $1,100 for a typical repair**, per HomeGuide flat-roof cost data. A minor leak runs $150 to $500, and an extensive leak with structural damage runs $1,200 to $3,000, per Angi."],
  ['flat-roof-installation-repair-decision', 's0b0', "**A flat roof's advantages are three membrane systems that match the building, plus a reflective white TPO that cuts cooling load**. EPDM lasts 15 to 25 years, TPO 7 to 20 years, and modified bitumen 20 years, per the InterNACHI life-expectancy chart."],
  ['flat-roof-installation-repair-decision', 's1b0', "**A flat roof's drawbacks are a shorter life than steep-slope or built-up roofing, seams that fail before the membrane field, and a low slope that turns one failed seam into a large water risk**, per InterNACHI and the NRCA."],
  ['tile-roof-installation-repair-signs', 'directAnswer', "**The signs you need tile roof work are interior stains beneath a tile roof 30 years or older, cracked, chipped, or displaced tiles, tiles sliding out of alignment, cracked ridge or hip mortar, and concrete-tile spalling or efflorescence**, per the Tile Roofing Industry Alliance and the InterNACHI life-expectancy chart."],
  ['tile-roof-installation-repair-signs', 's0b0', "**Interior stains beneath a tile roof 30 years or older** indicate failed underlayment rather than failed tile, because the underlayment, not the tile, sets the lifespan limiter, per the Tile Roofing Industry Alliance. Clay tile lasts 100 years or more, so a 30-to-50-year-old roof commonly needs underlayment replacement beneath tiles that remain sound, per the InterNACHI life-expectancy chart."],
  ['tile-roof-installation-repair-signs', 's1b0', "**Cracked, chipped, or displaced tiles** expose the underlayment to wind-driven rain, because a tile roof carries no field redundancy once a tile breaks. Broken tiles trace mostly to foot-traffic and impact rather than material failure, and a cracked tile gets removed and replaced individually at $50 to $300 per tile, per the Tile Roofing Industry Alliance and HomeGuide tile-repair cost data."],
  ['tile-roof-installation-repair-cost-guide', 's0b0', "**Tile roof repair** costs $5 to $25 per square foot, or roughly $500 to $2,500 in total, per HomeGuide tile-repair cost data. Concrete tile runs $9 to $18 per square foot and clay tile $12 to $25, per Modernize and HomeGuide."],
  ['tile-roof-installation-repair-cost-guide', 's1b0', "**The material tier and the failed layer** drive a tile roof's price. Clay costs more per square foot than concrete, and whether the failure is the tile, the fastening, or the underlayment beneath sets the scope, per the Tile Roofing Industry Alliance and HomeGuide."],
  ['tile-roof-installation-repair-decision', 's2b0', "**Tile fits an Essex County home whose framing carries the load** and an owner wanting a 100-year-plus clay cover or a 40-to-75-year concrete cover, per the InterNACHI life-expectancy chart and the Tile Roofing Industry Alliance. The covering sits over the underlayment that holds the waterproofing, and a structural assessment confirms the framing before installation."],
  ['cedar-shake-roofing-signs', 'directAnswer', "**The signs you need cedar shake roofing are a roof at or past its 20-to-40-year life, shakes cupped, curled, or split, a shake that cracks under the flex test, deep moss or lichen, or deck decay across 15%** (Cedar Shake and Shingle Bureau / InterNACHI / This Old House)."],
  ['cedar-shake-roofing-signs', 's0b0', "**A cedar shake roof reaches end-of-life at 20 to 40 years**, per the Cedar Shake and Shingle Bureau, against the single \"Wood\" service life of 25 years on the InterNACHI life-expectancy chart. Moisture management rather than the cedar itself sets the lifespan."],
  ['cedar-shake-roofing-cost-guide', 's0b0', "**Cedar shake roofing installs at $10 to $20 or more per square foot in New Jersey**, per NHI Contractors NJ pricing. Cedar shake repair runs $400 to $1,800, and preservative and cleaning maintenance runs $0.15 to $0.60 per square foot every few years, per Angi and HomeGuide."],
  ['cedar-shake-roofing-decision', 's1b0', "**Cedar shake's drawbacks center on moisture**: moisture management sets the lifespan, and the assembly needs at least 1.5 inches of air space or it decays early, per Cedar Shake and Shingle Bureau and NRCA guidance. North and shaded slopes degrade faster, the field demands recurring preservative and cleaning, and moisture, not insects, drives most premature cedar failure."],
  ['cedar-shake-roofing-decision', 's2b0', "**Cedar shake fits an Essex County home** whose character calls for cedar's natural look over a ventilated deck with at least 1.5 inches of underside air space, per Cedar Shake and Shingle Bureau guidance. The home's owner stays committed to the recurring preservative and cleaning cadence, and the ventilation path determines whether the cedar reaches its full 20-to-40-year life."],
  ['rubber-roofing-epdm-signs', 's2b0', "**Ponding water remaining more than 48 hours** counts as a defect that stretches and degrades the EPDM membrane, because a flat roof needs at least one-quarter inch per foot of slope to drain, per the NRCA and ARMA. Standing water weighs roughly 5 pounds per inch per square foot and deflects the deck into a deepening pond, so drainage correction restores the slope that keeps the membrane from sitting in water."],
];

let applied = 0;
for (const [id, field, value] of TRIMS) {
  const a = byId.get(id);
  if (!a) { console.error(`MISSING article ${id}`); process.exit(1); }
  if (field === 'directAnswer') {
    a.directAnswer = value;
  } else {
    const m = field.match(/^s(\d+)b0$/);
    if (!m) { console.error(`bad field ${field}`); process.exit(1); }
    const idx = Number(m[1]);
    if (!a.sections[idx]) { console.error(`${id} has no section ${idx}`); process.exit(1); }
    a.sections[idx].body[0] = value;
  }
  applied += 1;
}

writeFileSync(F, JSON.stringify({ articles: data.articles }, null, 2));
console.log(`Applied ${applied} trims -> ${F}`);
